// /* purpose to learn naming file by _number_file.rs */
mod _10_memory_management_ownership;
mod _11_string;
mod _12_if_expression;
mod _13_yo_loop;
mod _14_while_loop;
mod _15_for_loop;
mod _16_function;
mod _17_yo_ownership_function;
mod _18_yo_slice;
mod _19_yo_slice_string;
mod _1_variables;
mod _20_yo_struct;
mod _21_yo_method;
mod _22_enum;
mod _23_yo_pattern_matching;
mod _24_yo_type_alias;
mod _25_yo_module;
mod _26_yo_crate;
mod _27_yo_trait;
mod _28_generic;
mod _29_yo_overloadable_operator;
mod _2_data_types;
mod _30_yo_optional;
mod _31_yo_comparing;
mod _32_yo_string_manipulation;
mod _33_yo_formatting;
mod _34_yo_closure;
mod _3_numbers;
mod _4_operators_comparison;
mod _5_operator_boolean;
mod _6_char;
mod _7_array;
mod _8_constant;
mod _9_variable_scope;
fn main() {
    println!("Hello, world!");

    println!("\n=========variables=========");
    _1_variables::main();
    println!("\n=========data_types=========");
    _2_data_types::main();
    println!("\n=========numbers=========");
    _3_numbers::main();
    println!("\n=========comparsion_operator=========");
    _4_operators_comparison::main();
    println!("\n=========boolean_operator=========");
    _5_operator_boolean::main();
    println!("\n=========char=========");
    _6_char::main();
    println!("\n=========array=========");
    _7_array::main();
    println!("\n=========constant=========");
    _8_constant::main();
    println!("\n=========variable scope=========");
    _9_variable_scope::main();
    println!("\n=========memory_management=========");
    _10_memory_management_ownership::main();
    println!("\n=========string=========");
    _11_string::main();
    println!("\n=========if_expression=========");
    _12_if_expression::main();
    println!("\n=========loop=========");
    _13_yo_loop::main();
    println!("\n=========while loop=========");
    _14_while_loop::main();
    println!("\n=========for loop=========");
    _15_for_loop::main();
    println!("\n=========function loop=========");
    _16_function::main();
    println!("\n=========ownership=========");
    _17_yo_ownership_function::main();
    _18_yo_slice::main();
    _19_yo_slice_string::main();
    _20_yo_struct::main();
    _21_yo_method::main();
    _22_enum::main();
    _23_yo_pattern_matching::main();
    _24_yo_type_alias::main();
    _25_yo_module::main();
    _26_yo_crate::main();
    _27_yo_trait::main();
    _28_generic::main();
    _29_yo_overloadable_operator::main();
    _30_yo_optional::main();
    _31_yo_comparing::main();
    _32_yo_string_manipulation::main();
    _33_yo_formatting::main();
    _34_yo_closure::main();
}
