// /* purpose to learn naming file by _number_file.rs */
mod _10_memory_management_ownership;
mod _11_string;
mod _12_if_expression;
mod _13_yo_loop;
mod _14_while_loop;
mod _15_for_loop;
mod _16_function;
mod _17_yo_ownership_function;
mod _18_yo_slice;
mod _19_yo_slice_string;
mod _1_variables;
mod _2_data_types;
mod _3_numbers;
mod _4_operators_comparison;
mod _5_operator_boolean;
mod _6_char;
mod _7_array;
mod _8_constant;
mod _9_variable_scope;

fn main() {
    println!("Hello, world!");

    println!("\n=========variables=========");
    _1_variables::main();
    println!("\n=========data_types=========");
    _2_data_types::main();
    println!("\n=========numbers=========");
    _3_numbers::main();
    println!("\n=========comparsion_operator=========");
    _4_operators_comparison::main();
    println!("\n=========boolean_operator=========");
    _5_operator_boolean::main();
    println!("\n=========char=========");
    _6_char::main();
    println!("\n=========array=========");
    _7_array::main();
    println!("\n=========constant=========");
    _8_constant::main();
    println!("\n=========variable scope=========");
    _9_variable_scope::main();
    println!("\n=========memory_management=========");
    _10_memory_management_ownership::main();
    println!("\n=========string=========");
    _11_string::main();
    println!("\n=========if_expression=========");
    _12_if_expression::main();
    println!("\n=========loop=========");
    _13_yo_loop::main();
    println!("\n=========while loop=========");
    _14_while_loop::main();
    println!("\n=========for loop=========");
    _15_for_loop::main();
    println!("\n=========function loop=========");
    _16_function::main();
    println!("\n=========ownership=========");
    _17_yo_ownership_function::main();
    _18_yo_slice::main();
    _19_yo_slice_string::main();
}
